/**
 * AUTO-GENERATED by scripts/write-build-info.cjs — do not edit by hand.
 * Safe public deployment identity only (no secrets).
 */
export const BUILD_INFO = {
  "applicationVersion": "0.1.0",
  "gitSha": "unknown",
  "buildTimestamp": "unknown",
  "environmentName": "local",
  "workerName": "bfa-sms-staging"
} as const;
